version: '2'

services:
  reporter:
    image: mapzen/ot-reporter:latest
    networks:
      - opentraffic
    ports:
      - "8002:8002"
    expose:
      - "8002"
    volumes:
      - ${DATAPATH}:/data/valhalla

networks:
  opentraffic:
    driver: bridge
