version: '2'

services:
  postgres:
    image: postgres:9.6.1
    networks:
      - opentraffic_datastore
    ports:
      - "5432:5432"
    volumes:
      - ${PGDATA}:/data
    environment:
      - POSTGRES_USER=opentraffic
      - POSTGRES_DB=opentraffic
      - POSTGRES_PASSWORD=changeme
      - PGDATA=/data/postgres

  datastore:
    image: opentraffic/datastore:latest
    networks:
      - opentraffic_datastore
    ports:
      - "8003:8003"
    volumes:
      - ${DATAPATH}:/data
    environment:
      - POSTGRES_USER=opentraffic
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=opentraffic
      - POSTGRES_HOST=postgres

  redis:
    image: redis:3.2.6
    networks:
      - opentraffic
    ports:
      - "6379:6379"

  reporter:
    image: opentraffic/reporter:latest
    networks:
      - opentraffic
    ports:
      - "8002:8002"
    volumes:
      - ${DATAPATH}:/data/valhalla
    environment:
      - REDIS_HOST=redis
      - DATASTORE_URL=http://datastore:8003/store?

networks:
  opentraffic:
    driver: bridge
